service_principal_name = "aks-project2-spn"
subscription_path      = "/subscriptions/75e2cef5-d3ca-42ff-8b0d-4dab256b9453"
keyvault_name          = "aks-project2"
ado_org_service_url    = "https://dev.azure.com/utft0"
project_name = "Aks-Terra"
