variable "RESOURCE_GROUP_NAME" { type = string }
variable "LOCATION" { type = string }
variable "COLLATION" { type = string }
variable "DB_NAME" { type = string }
variable "DBPASSWORD" { type = string }
variable "DBSERVER_NAME" { type = string }
variable "DBUSERNAME" { type = string }
variable "AKS_SUBNET_ID" { type = string }
variable "AKS_SUBNET_SERVICE_ENDPOINT" {type = string}