trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - template: pipelines/terraform-deploy.yaml
      parameters:
        environment: 'terrafrom'

- stage: Stage2
  dependsOn: Stage1
  condition: succeeded()
  jobs:
  - job: Job2
    steps:
    - template: pipelines/project-deploy.yaml
      parameters:
        environment: 'app'

