apiVersion: v1
kind: Secret
metadata:
  name: db-connection-secret
type: Opaque
data:
  connection-string: base64-encoded-database-string

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata: 
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: myprivateacr1.azurecr.io/aks-terra-main:v1
        ports:
        - containerPort: 80
        env:
        - name: CONNECTION_STRING_FROM_SECRET
          valueFrom:
            secretKeyRef:
              name: db-connection-secret
              key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80
